/**
 * Created by wangj on 2016/11/15.
 */

var config = {
    rich: {
        whiteList: {
            a:      ['target', 'href', 'title','_href'],
            abbr:   ['title'],
            address: [],
            area:   ['shape', 'coords', 'href', 'alt'],
            article: [],
            aside:  [],
            b:      [],
            bdi:    ['dir'],
            bdo:    ['dir'],
            big:    [],
            blockquote: ['cite'],
            br:     [],
            caption: [],
            center: [],
            cite:   [],
            code:   [],
            col:    ['align', 'valign', 'span', 'width'],
            colgroup: ['align', 'valign', 'span', 'width'],
            dd:     [],
            del:    ['datetime'],
            details: ['open'],
            div:    [],
            dl:     [],
            dt:     [],
            em:     [],
            embed:  ['type', 'class', 'pluginspage', 'src', 'width', 'height', 'wmode', 'play', 'loop', 'menu', 'allowfullscreen'],
            font:   ['color', 'size', 'face'],
            footer: [],
            h1:     [],
            h2:     [],
            h3:     [],
            h4:     [],
            h5:     [],
            h6:     [],
            header: [],
            hr:     [],
            i:      [],
            img:    ['src', 'alt', 'title', 'width', 'height','title_src','data-src'],
            ins:    ['datetime'],
            li:     [],
            mark:   [],
            nav:    [],
            ol:     [],
            p:      ["style"],
            path:   ["d"],
            pre:    ["class"],
            s:      [],
            section:[],
            small:  [],
            span:   ["style"],
            sub:    [],
            sup:    [],
            strong: ["style"],
            svg:    ["aria-hidden", "class", "height", "version", "viewbox", "width"],
            table:  ['width', 'border', 'align', 'valign'],
            tbody:  ['align', 'valign'],
            td:     ['width', 'colspan', 'align', 'valign'],
            tfoot:  ['align', 'valign'],
            th:     ['width', 'colspan', 'align', 'valign'],
            thead:  ['align', 'valign'],
            tr:     ['rowspan', 'align', 'valign'],
            tt:     [],
            u:      [],
            ul:     []
        }
    },
    richWithIframe: {
        whiteList: {
            a:      ['target', 'href', 'title','_href'],
            abbr:   ['title'],
            address: [],
            area:   ['shape', 'coords', 'href', 'alt'],
            article: [],
            aside:  [],
            b:      [],
            bdi:    ['dir'],
            bdo:    ['dir'],
            big:    [],
            blockquote: ['cite'],
            br:     [],
            caption: [],
            center: [],
            cite:   [],
            code:   [],
            col:    ['align', 'valign', 'span', 'width'],
            colgroup: ['align', 'valign', 'span', 'width'],
            dd:     [],
            del:    ['datetime'],
            details: ['open'],
            div:    [],
            dl:     [],
            dt:     [],
            em:     [],
            embed:  ['type', 'class', 'pluginspage', 'src', 'width', 'height', 'wmode', 'play', 'loop', 'menu', 'allowfullscreen'],
            font:   ['color', 'size', 'face'],
            footer: [],
            h1:     [],
            h2:     [],
            h3:     [],
            h4:     [],
            h5:     [],
            h6:     [],
            header: [],
            hr:     [],
            i:      [],
            iframe: ["frameborder", "width", "height", "src", "allowfullscreen"],
            img:    ['src', 'alt', 'title', 'width', 'height','title_src','data-src'],
            ins:    ['datetime'],
            li:     [],
            mark:   [],
            nav:    [],
            ol:     [],
            p:      ["style"],
            path:   ["d"],
            pre:    ["class"],
            s:      [],
            section:[],
            small:  [],
            span:   ["style"],
            sub:    [],
            sup:    [],
            strong: ["style"],
            svg:    ["aria-hidden", "class", "height", "version", "viewbox", "width"],
            table:  ['width', 'border', 'align', 'valign'],
            tbody:  ['align', 'valign'],
            td:     ['width', 'colspan', 'align', 'valign'],
            tfoot:  ['align', 'valign'],
            th:     ['width', 'colspan', 'align', 'valign'],
            thead:  ['align', 'valign'],
            tr:     ['rowspan', 'align', 'valign'],
            tt:     [],
            u:      [],
            ul:     []
        }
    },
    pOnly: {
        whiteList: {
            p: []
        }
    },
    plain: {
        whiteList: {
        }
    }
};

module.exports = config;